import { createI18n, getUiLang } from '@genoffice/i18n'

const tDlg = createI18n({
  zh: {
    dlgSaveTitle: '保存韩文文档',
    filterHwp: '韩文文档',
    filterHwpx: '韩文 HWPX 文档',
    filterHml: '韩文 HML 文档',
    untitledFile: '未命名韩文',
    closeUnsavedMsg: '此文档有未保存的更改。',
    closeUnsavedDetail: '关闭前是否保存？',
    btnSave: '保存',
    btnDontSave: '不保存',
    btnCancel: '取消',
  },
  en: {
    dlgSaveTitle: 'Save Hangul Document',
    filterHwp: 'Hangul Documents',
    filterHwpx: 'Hangul HWPX Documents',
    filterHml: 'Hangul HML Documents',
    untitledFile: 'Untitled Hangul',
    closeUnsavedMsg: 'This document has unsaved changes.',
    closeUnsavedDetail: 'Do you want to save them before closing?',
    btnSave: 'Save',
    btnDontSave: "Don't Save",
    btnCancel: 'Cancel',
  },
  ja: {
    dlgSaveTitle: 'ハングル文書を保存',
    filterHwp: 'ハングル文書',
    filterHwpx: 'ハングル HWPX 文書',
    filterHml: 'ハングル HML 文書',
    untitledFile: '無題のハングル',
    closeUnsavedMsg: 'このドキュメントに未保存の変更があります。',
    closeUnsavedDetail: '閉じる前に保存しますか？',
    btnSave: '保存',
    btnDontSave: '保存しない',
    btnCancel: 'キャンセル',
  },
  ko: {
    dlgSaveTitle: '한글 문서 저장',
    filterHwp: '한글 문서',
    filterHwpx: '한글 HWPX 문서',
    filterHml: '한글 HML 문서',
    untitledFile: '제목 없는 한글',
    closeUnsavedMsg: '이 문서에 저장하지 않은 변경 사항이 있습니다.',
    closeUnsavedDetail: '닫기 전에 저장하시겠습니까?',
    btnSave: '저장',
    btnDontSave: '저장 안 함',
    btnCancel: '취소',
  },
  fr: {
    dlgSaveTitle: 'Enregistrer le document Hangul',
    filterHwp: 'Documents Hangul',
    filterHwpx: 'Documents Hangul HWPX',
    filterHml: 'Documents Hangul HML',
    untitledFile: 'Hangul sans titre',
    closeUnsavedMsg: 'Ce document contient des modifications non enregistrées.',
    closeUnsavedDetail: 'Voulez-vous les enregistrer avant de fermer ?',
    btnSave: 'Enregistrer',
    btnDontSave: 'Ne pas enregistrer',
    btnCancel: 'Annuler',
  },
  de: {
    dlgSaveTitle: 'Hangul-Dokument speichern',
    filterHwp: 'Hangul-Dokumente',
    filterHwpx: 'Hangul-HWPX-Dokumente',
    filterHml: 'Hangul-HML-Dokumente',
    untitledFile: 'Unbenanntes Hangul',
    closeUnsavedMsg: 'Dieses Dokument enthält ungespeicherte Änderungen.',
    closeUnsavedDetail: 'Vor dem Schließen speichern?',
    btnSave: 'Speichern',
    btnDontSave: 'Nicht speichern',
    btnCancel: 'Abbrechen',
  },
  es: {
    dlgSaveTitle: 'Guardar documento Hangul',
    filterHwp: 'Documentos Hangul',
    filterHwpx: 'Documentos Hangul HWPX',
    filterHml: 'Documentos Hangul HML',
    untitledFile: 'Hangul sin título',
    closeUnsavedMsg: 'Este documento tiene cambios sin guardar.',
    closeUnsavedDetail: '¿Quieres guardarlos antes de cerrar?',
    btnSave: 'Guardar',
    btnDontSave: 'No guardar',
    btnCancel: 'Cancelar',
  },
  th: {
    dlgSaveTitle: 'บันทึกเอกสารฮันกึล',
    filterHwp: 'เอกสารฮันกึล',
    filterHwpx: 'เอกสารฮันกึล HWPX',
    filterHml: 'เอกสารฮันกึล HML',
    untitledFile: 'ฮันกึลไม่มีชื่อ',
    closeUnsavedMsg: 'เอกสารนี้มีการเปลี่ยนแปลงที่ยังไม่ได้บันทึก',
    closeUnsavedDetail: 'ต้องการบันทึกก่อนปิดหรือไม่?',
    btnSave: 'บันทึก',
    btnDontSave: 'ไม่บันทึก',
    btnCancel: 'ยกเลิก',
  },
  id: {
    dlgSaveTitle: 'Simpan dokumen Hangul',
    filterHwp: 'Dokumen Hangul',
    filterHwpx: 'Dokumen Hangul HWPX',
    filterHml: 'Dokumen Hangul HML',
    untitledFile: 'Hangul tanpa judul',
    closeUnsavedMsg: 'Dokumen ini memiliki perubahan yang belum disimpan.',
    closeUnsavedDetail: 'Simpan sebelum menutup?',
    btnSave: 'Simpan',
    btnDontSave: 'Jangan Simpan',
    btnCancel: 'Batal',
  },
  ru: {
    dlgSaveTitle: 'Сохранить документ Хангыль',
    filterHwp: 'Документы Хангыль',
    filterHwpx: 'Документы Хангыль HWPX',
    filterHml: 'Документы Хангыль HML',
    untitledFile: 'Хангыль без названия',
    closeUnsavedMsg: 'В этом документе есть несохранённые изменения.',
    closeUnsavedDetail: 'Сохранить их перед закрытием?',
    btnSave: 'Сохранить',
    btnDontSave: 'Не сохранять',
    btnCancel: 'Отмена',
  },
  ar: {
    dlgSaveTitle: 'حفظ مستند هانغل',
    filterHwp: 'مستندات هانغل',
    filterHwpx: 'مستندات هانغل HWPX',
    filterHml: 'مستندات هانغل HML',
    untitledFile: 'هانغل بدون عنوان',
    closeUnsavedMsg: 'يحتوي هذا المستند على تغييرات غير محفوظة.',
    closeUnsavedDetail: 'هل تريد حفظها قبل الإغلاق؟',
    btnSave: 'حفظ',
    btnDontSave: 'عدم الحفظ',
    btnCancel: 'إلغاء',
  },
  pt: {
    dlgSaveTitle: 'Salvar documento Hangul',
    filterHwp: 'Documentos Hangul',
    filterHwpx: 'Documentos Hangul HWPX',
    filterHml: 'Documentos Hangul HML',
    untitledFile: 'Hangul sem título',
    closeUnsavedMsg: 'Este documento tem alterações não salvas.',
    closeUnsavedDetail: 'Deseja salvá-las antes de fechar?',
    btnSave: 'Salvar',
    btnDontSave: 'Não Salvar',
    btnCancel: 'Cancelar',
  },
  it: {
    dlgSaveTitle: 'Salva documento Hangul',
    filterHwp: 'Documenti Hangul',
    filterHwpx: 'Documenti Hangul HWPX',
    filterHml: 'Documenti Hangul HML',
    untitledFile: 'Hangul senza titolo',
    closeUnsavedMsg: 'Questo documento contiene modifiche non salvate.',
    closeUnsavedDetail: 'Vuoi salvarle prima di chiudere?',
    btnSave: 'Salva',
    btnDontSave: 'Non salvare',
    btnCancel: 'Annulla',
  },
  pl: {
    dlgSaveTitle: 'Zapisz dokument Hangul',
    filterHwp: 'Dokumenty Hangul',
    filterHwpx: 'Dokumenty Hangul HWPX',
    filterHml: 'Dokumenty Hangul HML',
    untitledFile: 'Hangul bez tytułu',
    closeUnsavedMsg: 'Ten dokument ma niezapisane zmiany.',
    closeUnsavedDetail: 'Czy zapisać je przed zamknięciem?',
    btnSave: 'Zapisz',
    btnDontSave: 'Nie zapisuj',
    btnCancel: 'Anuluj',
  },
  cs: {
    dlgSaveTitle: 'Uložit dokument Hangul',
    filterHwp: 'Dokumenty Hangul',
    filterHwpx: 'Dokumenty Hangul HWPX',
    filterHml: 'Dokumenty Hangul HML',
    untitledFile: 'Hangul bez názvu',
    closeUnsavedMsg: 'Tento dokument obsahuje neuložené změny.',
    closeUnsavedDetail: 'Chcete je před zavřením uložit?',
    btnSave: 'Uložit',
    btnDontSave: 'Neukládat',
    btnCancel: 'Zrušit',
  },
  nl: {
    dlgSaveTitle: 'Hangul-document opslaan',
    filterHwp: 'Hangul-documenten',
    filterHwpx: 'Hangul-HWPX-documenten',
    filterHml: 'Hangul-HML-documenten',
    untitledFile: 'Naamloos Hangul',
    closeUnsavedMsg: 'Dit document bevat niet-opgeslagen wijzigingen.',
    closeUnsavedDetail: 'Wilt u ze opslaan voordat u sluit?',
    btnSave: 'Opslaan',
    btnDontSave: 'Niet opslaan',
    btnCancel: 'Annuleren',
  },
  ms: {
    dlgSaveTitle: 'Simpan dokumen Hangul',
    filterHwp: 'Dokumen Hangul',
    filterHwpx: 'Dokumen Hangul HWPX',
    filterHml: 'Dokumen Hangul HML',
    untitledFile: 'Hangul tanpa tajuk',
    closeUnsavedMsg: 'Dokumen ini mempunyai perubahan yang belum disimpan.',
    closeUnsavedDetail: 'Simpan sebelum menutup?',
    btnSave: 'Simpan',
    btnDontSave: 'Jangan Simpan',
    btnCancel: 'Batal',
  },
  he: {
    dlgSaveTitle: 'שמירת מסמך האנגול',
    filterHwp: 'מסמכי האנגול',
    filterHwpx: 'מסמכי האנגול HWPX',
    filterHml: 'מסמכי האנגול HML',
    untitledFile: 'האנגול ללא שם',
    closeUnsavedMsg: 'במסמך הזה יש שינויים שלא נשמרו.',
    closeUnsavedDetail: 'האם לשמור אותם לפני הסגירה?',
    btnSave: 'שמירה',
    btnDontSave: 'אל תשמור',
    btnCancel: 'ביטול',
  },
  hi: {
    dlgSaveTitle: 'हंगुल दस्तावेज़ सहेजें',
    filterHwp: 'हंगुल दस्तावेज़',
    filterHwpx: 'हंगुल HWPX दस्तावेज़',
    filterHml: 'हंगुल HML दस्तावेज़',
    untitledFile: 'अनाम हंगुल',
    closeUnsavedMsg: 'इस दस्तावेज़ में सहेजे नहीं गए परिवर्तन हैं।',
    closeUnsavedDetail: 'क्या बंद करने से पहले उन्हें सहेजना चाहते हैं?',
    btnSave: 'सहेजें',
    btnDontSave: 'न सहेजें',
    btnCancel: 'रद्द करें',
  },
  'zh-TW': {
    dlgSaveTitle: '儲存韓文文件',
    filterHwp: '韓文文件',
    filterHwpx: '韓文 HWPX 文件',
    filterHml: '韓文 HML 文件',
    untitledFile: '未命名韓文',
    closeUnsavedMsg: '此文件有未儲存的變更。',
    closeUnsavedDetail: '關閉前是否儲存？',
    btnSave: '儲存',
    btnDontSave: '不儲存',
    btnCancel: '取消',
  },
})

export type DlgKey =
  | 'dlgSaveTitle'
  | 'filterHwp'
  | 'filterHwpx'
  | 'filterHml'
  | 'untitledFile'
  | 'closeUnsavedMsg'
  | 'closeUnsavedDetail'
  | 'btnSave'
  | 'btnDontSave'
  | 'btnCancel'

export const tm = (key: DlgKey) => tDlg(getUiLang(), key)
